# Generated by Django 5.2.5 on 2025-08-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janela', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='idade',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(default=''),
        ),
    ]
