# Generated by Django 5.2.5 on 2025-08-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janela', '0002_remove_usuarios_idade_usuarios_email_usuarios_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
